version: '3'
services:
  nginx:
    image: "nginx:latest"
    container_name: web-youtube-downloader
    volumes:
      - $PWD:/code:ro
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD/log:/var/log/nginx/
    ports:
      - 8080:80
    restart: always
